applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argo-cd
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 6.2.1
        helm:
          version: v3
          valueFiles:
            - $values/argocd-values.yaml
      - repoURL: https://github.com/pasquale-jp/argocd-apps-test.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argocd-apps
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 1.6.1
        helm:
          version: v3
          valueFiles:
            - $values/argocd-apps-gloo-values.yaml
      - repoURL: https://github.com/pasquale-jp/argocd-apps-test.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - ApplyOutOfSyncOnly=true
  - name: gloo
    namespace: argocd
    destination:
      namespace: gloo-system
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: gloo
        repoURL: https://storage.googleapis.com/solo-public-helm
        targetRevision: v1.16.4
        helm:
          values: |
            discovery:
              enabled: false
            gateway:
              certGenJob:
                enabled: false
            gatewayProxies:
              gatewayProxy:
                disabled: true
            settings:
              disableKubernetesDestinations: true
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
projects:
  - name: jp-system
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: System services
    sourceRepos:
      - https://argoproj.github.io/argo-helm
      - https://github.com/pasquale-jp/argocd-apps-test.git
      - https://storage.googleapis.com/solo-public-helm
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: gloo-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
