applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argo-cd
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 6.2.1
        helm:
          version: v3
          valueFiles:
            - $values/argocd-values.yaml
      - repoURL: https://github.com/pasquale-jp/argocd-apps-test.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argocd-apps
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 1.6.1
        helm:
          version: v3
          valueFiles:
            - $values/argocd-apps-github-arc-values.yaml
      - repoURL: https://github.com/pasquale-jp/argocd-apps-test.git
        targetRevision: HEAD
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - ApplyOutOfSyncOnly=true
  - name: action-runner-controller
    namespace: argocd
    destination:
      namespace: arc-systems
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: gha-runner-scale-set-controller
        repoURL: ghcr.io/actions/actions-runner-controller-charts
        targetRevision: 0.8.3
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
  - name: arc-runner-set
    namespace: argocd
    destination:
      namespace: arc-runners
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: gha-runner-scale-set
        repoURL: ghcr.io/actions/actions-runner-controller-charts
        targetRevision: 0.8.3
        helm:
          version: v3
          values: |
            githubConfigUrl: https://github.com/JillionPay/infra
            githubConfigSecret: pre-defined-secret
            controllerServiceAccount:
              namespace: arc-systems
              name: action-runner-controller-gha-rs-controller
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
projects:
  - name: jp-system
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: System services
    sourceRepos:
      - https://argoproj.github.io/argo-helm
      - https://github.com/pasquale-jp/argocd-apps-test.git
      - https://storage.googleapis.com/solo-public-helm
      - ghcr.io/actions/actions-runner-controller-charts
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: arc-runners
        server: https://kubernetes.default.svc
      - namespace: arc-systems
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
