applications:
  - name: argocd
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argo-cd
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 6.2.1
        helm:
          version: v3
          valueFiles:
            - $values/staging/argocd/argocd-values.yaml
      - repoURL: git@github.com:JillionPay/infra.git
        targetRevision: dev
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
  - name: argocd-apps
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: jp-system
    sources:
      - chart: argocd-apps
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 1.6.1
        helm:
          version: v3
          valueFiles:
            - $values/staging/argocd/argocd-apps-values.yaml
      - repoURL: git@github.com:JillionPay/infra.git
        targetRevision: dev
        ref: values
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - ApplyOutOfSyncOnly=true
  - name: payment-service
    namespace: argocd
    destination:
      namespace: product
      server: https://kubernetes.default.svc
    project: product
    sources:
      - path: chart
        repoURL: https://github.com/henrywhitaker3/generic-helm-chart
        targetRevision: 5110b3ce43d9e5fb681de48119a5b0f0a1e329f3
        helm:
          values: |
            image:
              repository: 381492207002.dkr.ecr.me-central-1.amazonaws.com/staging-payments
              tag: 0.0.3
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
projects:
  - name: jp-system
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: System services
    sourceRepos:
      - git@github.com:JillionPay/infra.git
      - https://argoproj.github.io/argo-helm
      - https://github.com/henrywhitaker3/generic-helm-chart
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
  - name: product
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Product services
    sourceRepos:
      - git@github.com:JillionPay/infra.git
      - https://argoproj.github.io/argo-helm
      - https://github.com/henrywhitaker3/generic-helm-chart
    destinations:
      - namespace: product
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
